# Generated by Django 5.1.6 on 2025-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpost_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(default='basketball.jpg', upload_to='blog_images/'),
        ),
    ]
